### ISSUE TITLE
开源软件重名

### ISSUE THREAD

**Issue by zhangxianweihebei** [Sproutigy/LucenePlus#1]
您好 很巧啊   我的开源软件也叫LucenePlus

**Comment by LukeAheadNet** [comment]
Hi @zhangxianweihebei ! Google Translator says that you wrote comment "Hi, my open source software is also called LucenePlus". If you can, please use English. I've checked your repositories under: https://github.com/zhangxianweihebei?tab=repositories and haven't found "LucenePlus" there.
Other similarly named repositories found on GitHub are:
- https://github.com/7897ewrr/LucenePlus - no updates from 2 years, no releases
- https://github.com/yangyining/lucene-plus - no updates from a year, no releases, no documentation

Sorry for naming conflict, this wasn't my intention.

Seems that mine library is the only one released to Public Maven repository right now using that name: https://mvnrepository.com/search?q=luceneplus
As it is already released to Public Maven, I cannot rename it.

Please treat this library as fully namespaced *com.sproutigy.libs.luceneplus*, so there will be no code conflicts with your library.

**Comment by zhangxianweihebei** [comment]
You misunderstood, I just want to say very clever, I have been using their own personal service, so you can not see, I released an open source git in China
